### ISSUE TITLE
remove ufo hotline

### ISSUE THREAD

**Issue by kra** [futel/asteriskserver#509]
the hotline guy called back to complain about non-ufo calls more than once
while it is fun to connect people to him, I hate to bother a believer
maybe add our own ufo hotline? just record sightings after warning caller that recordings may be published?

**Comment by breedx2** [comment]
Honestly, without a related PR linked to #253 it makes it much harder to track stuff down....but finally found it. Just searching `ufo` in this repo doesn't hit, because it's `nuforc` and github search is weak. But anyway, [found it](https://github.com/futel/asteriskserver/commit/8784a008263e93a653ed8a651fea0d97889057af#diff-5e0602cd0dbdcfee3046f13123c4b4993ed69897d647168274afd63d9570d43fR36). 

Looks like [7 calls in the last year](https://futel.github.io/usage/?e=directory-nuforc&p=680%7C640%7C415%7C410%7C420%7C610%7C700%7C690%7C695%7C440%7Cvoipms%7Ctwilio-termination%7Cfutel.pstn.twilio.com%7C445%7C660%7C668%7C645%7C670%7C615%7C405%7C435%7C620%7C655%7C625%7C630&r=-1y).

**Comment by kra** [comment]
That usage graph can't be right, because the guy called the Saratoga phone to complain. But he did call the incoming line also, so maybe there was a rash of people calling from upright, which has the incoming line as the caller ID.

Anyway, I really like having it in the directory, and I really like getting amusing calls from the guy running it, but I feel like we should treat him as an ally and not as a content generator haha

-------- Original Message --------
